FROM node:22-bookworm-slim AS build
WORKDIR /app

# Debian already has CA bundle installed, but this doesn't hurt
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*

ARG BUILD_CONFIGURATION=production

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build -- --configuration=$BUILD_CONFIGURATION

# --- runtime stage ---
FROM nginx:stable-alpine

# Replace default nginx config
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf


COPY --from=build /app/dist/lifex-config-frontend/browser/ /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
